apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ghostfolio
  labels:
    app: ghostfolio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ghostfolio.port }}
      protocol: TCP
      name: http